#!/bin/bash
SOLVING_PROCEDURE=풀이과정.md
LANGUAGE_EXT=cpp

function new_problem() {
	DIR_NAME=$1
	set -e
	mkdir $DIR_NAME
	sed "s/problem_name/$DIR_NAME/" ./$SOLVING_PROCEDURE > ./$DIR_NAME/$SOLVING_PROCEDURE
	touch ./$DIR_NAME/solution.$LANGUAGE_EXT
	set +e
}

function help_message() {
	cat <<HELP
Usage: ./ps_tool COMMAND

COMMAND			Description
help			show this message
new problem_name	create a new problem solving necessaries.

HELP
}


case $1 in
	new)
	shift 1
	new_problem $@
	;;
	*)
	help_message
	;;
esac